# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Hyprland Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Source Files                             ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
source = ~/.config/hypr/config/animations.conf                     # Animation Configuration
source = ~/.config/hypr/config/autostart.conf                      # Autostart Configuration
source = ~/.config/hypr/config/decorations.conf                    # Decorations Configuration
source = ~/.config/hypr/config/enviroment.conf                     # Environment Configuration
source = ~/.config/hypr/config/keybinds.conf                       # Keybinds Configuration
source = ~/.config/hypr/config/input.conf                          # Input Configuration
source = ~/.config/hypr/config/monitor.conf                        # Monitor Configuration
source = ~/.config/hypr/config/windowrules.conf                    # Window Rules Configuration