source = ~/.config/hypr/config/animations
source = ~/.config/hypr/config/autostart
source = ~/.config/hypr/config/decorations
source = ~/.config/hypr/config/input
source = ~/.config/hypr/config/keybinds
source = ~/.config/hypr/config/monitor
source = ~/.config/hypr/config/windowrules