# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Hyprland Autostart Configuration        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                   Startup Applications                      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
exec-once = ~/.config/waybar/theme_switcher.sh                               # Waybar Theme Switcher
exec-once = waypaper --restore                                               # Restore Last Wallpaper
exec-once = [workspace 2] vesktop                                            # Launch Vesktop on Workspace 2
exec-once = arrpc                                                            # Start arrpc
exec-once = solaar -w hide                                                   # Start Solaar (Hide Window)