windowrulev2 = workspace 3,title:^(steam)$
windowrulev2 = workspace 3,title:^(lutris)$
windowrulev2 = workspace 3,title:^(heroic)$
windowrulev2 = workspace 3,title:^(prism)$
windowrulev2 = workspace 3,title:^(steamapp)$

windowrulev2 = workspace 5,title:^(spotify)$
windowrulev2 = workspace 2,title:^(vesktop)$
