source = ~/rice/dotfiles/hyprland/animations.conf
source = ~/rice/dotfiles/hyprland/autostart.conf
source = ~/rice/dotfiles/hyprland/cursor.conf
source = ~/rice/dotfiles/hyprland/decorations.conf
source = ~/rice/dotfiles/hyprland/enviroments.conf
source = ~/rice/dotfiles/hyprland/keybinds.conf
source = ~/rice/dotfiles/hyprland/layout.conf
source = ~/rice/dotfiles/hyprland/monitor.conf
source = ~/rice/dotfiles/hyprland/window-decoration.conf
source = ~/rice/dotfiles/hyprland/windowrules.conf
