# ======= Workspace 1 =======


# ======= Workspace 2 =======
windowrule = workspace 2,title:^(.*Discord.*)$

# ======= Workspace 3 =======
windowrule = workspace 3,title:^(Steam)$
windowrule = workspace 3,title:^(Lutris)$
windowrule = workspace 3,title:^(.*Heroic.*)$
windowrule = workspace 3,title:^(.*Prism.*)$

# ======= Workspace 4 =======
windowrule = workspace 4, title:^(.*VSCodium.*)$
windowrule = workspace 4, title:^(.*Adobe Photoshop 2021.*)$
windowrule = workspace 4, title:^(.*Thunderbird.*)$

# ======= Workspace 5 =======
